const emojis = [
  // Estrellas y brillos
  { symbol: "✮", name: "estrella", tags: ["estrella", "brillo", "aesthetic"] },
  { symbol: "⋆", name: "estrella pequeña", tags: ["estrella", "bonito", "delicado"] },
  { symbol: "☆", name: "estrella contorno", tags: ["estrella", "simple"] },
  { symbol: "★", name: "estrella rellena", tags: ["estrella", "bold"] },
  { symbol: "✧", name: "brillo", tags: ["estrella", "aesthetic", "sparkle"] },
  { symbol: "✦", name: "estrella cuatro puntas", tags: ["estrella", "geometric"] },
  { symbol: "✩", name: "estrella estrés", tags: ["estrella", "vintage"] },
  { symbol: "✪", name: "estrella círculo", tags: ["estrella", "único"] },
  { symbol: "✫", name: "estrella abierta", tags: ["estrella", "delicado"] },
  { symbol: "✬", name: "estrella negra", tags: ["estrella", "bold"] },
  { symbol: "✭", name: "estrella contorno grueso", tags: ["estrella", "retro"] },
  { symbol: "✯", name: "estrella pinwheel", tags: ["estrella", "divertido"] },
  { symbol: "✰", name: "estrella sombra", tags: ["estrella", "3d"] },
  { symbol: "⚝", name: "estrella contorno doble", tags: ["estrella", "único"] },
  { symbol: "※", name: "marca referencia", tags: ["estrella", "símbolo"] },
  
  // Corazones
  { symbol: "♡", name: "corazón vacío", tags: ["amor", "bonito", "delicado"] },
  { symbol: "♥", name: "corazón relleno", tags: ["amor", "bold"] },
  { symbol: "❤", name: "corazón emoji", tags: ["amor", "rojo"] },
  { symbol: "𓆩♡𓆪", name: "corazón decorado", tags: ["amor", "aesthetic", "decorativo"] },
  { symbol: "ᰔ", name: "corazón mini", tags: ["amor", "pequeño", "bonito"] },
  { symbol: "ᰔᩚ", name: "corazón doble mini", tags: ["amor", "delicado"] },
  
  // Luna y cielo
  { symbol: "☾", name: "luna creciente", tags: ["noche", "luna", "aesthetic"] },
  { symbol: "☽", name: "luna menguante", tags: ["noche", "luna"] },
  { symbol: "☁", name: "nube", tags: ["cielo", "suave", "bonito"] },
  { symbol: "☀", name: "sol", tags: ["día", "brillante", "feliz"] },
  { symbol: "🌤", name: "sol tras nube", tags: ["día", "clima"] },
  
  // Flores y naturaleza
  { symbol: "𓆰", name: "mariposa", tags: ["naturaleza", "aesthetic", "insecto"] },
  { symbol: "𓆱", name: "flor", tags: ["naturaleza", "aesthetic", "planta"] },
  { symbol: "✿", name: "flor rellena", tags: ["naturaleza", "bonito", "flor"] },
  { symbol: "❀", name: "flor blanca", tags: ["naturaleza", "delicado", "flor"] },
  { symbol: "✾", name: "flor seis pétalos", tags: ["naturaleza", "flor"] },
  { symbol: "✽", name: "flor ocho pétalos", tags: ["naturaleza", "flor"] },
  { symbol: "❁", name: "flor contorno", tags: ["naturaleza", "simple", "flor"] },
  
  // Puntos y divisores
  { symbol: "˙", name: "punto", tags: ["minimal", "bonito", "pequeño"] },
  { symbol: "·", name: "punto medio", tags: ["separador", "minimal"] },
  { symbol: "•", name: "bullet", tags: ["punto", "lista"] },
  { symbol: "‧", name: "punto guion", tags: ["separador", "delicado"] },
  { symbol: "∘", name: "círculo pequeño", tags: ["geometric", "minimal"] },
  { symbol: "○", name: "círculo blanco", tags: ["geometric", "simple"] },
  { symbol: "●", name: "círculo negro", tags: ["geometric", "bold"] },
  { symbol: "◦", name: "bullet blanco", tags: ["lista", "delicado"] },
  { symbol: "⋅", name: "operador punto", tags: ["math", "minimal"] },
  { symbol: "⸰", name: "cinco puntos", tags: ["decorativo", "separador"] },
  { symbol: "⋆୨୧⋆", name: "estrellas con lazo", tags: ["decorativo", "aesthetic", "estrella"] },
  { symbol: "·:*¨༺", name: "divisor izquierdo", tags: ["decorativo", "vintage"] },
  { symbol: "༻¨*:·", name: "divisor derecho", tags: ["decorativo", "vintage"] },
  { symbol: "───", name: "línea", tags: ["separador", "línea"] },
  { symbol: "━━━", name: "línea gruesa", tags: ["separador", "bold"] },
  { symbol: "┈", name: "línea punteada", tags: ["separador", "delicado"] },
  { symbol: "┄", name: "línea guiones", tags: ["separador", "casual"] },
  
  // Flechas
  { symbol: "→", name: "flecha derecha", tags: ["flecha", "dirección"] },
  { symbol: "←", name: "flecha izquierda", tags: ["flecha", "dirección"] },
  { symbol: "↑", name: "flecha arriba", tags: ["flecha", "dirección"] },
  { symbol: "↓", name: "flecha abajo", tags: ["flecha", "dirección"] },
  { symbol: "⇢", name: "flecha derecha larga", tags: ["flecha", "decorativo"] },
  { symbol: "⇠", name: "flecha izquierda larga", tags: ["flecha", "decorativo"] },
  { symbol: "➜", name: "flecha derecha decorativa", tags: ["flecha", "aesthetic"] },
  { symbol: "➔", name: "flecha derecha simple", tags: ["flecha", "minimal"] },
  { symbol: "➝", name: "flecha derecha open", tags: ["flecha", "delicado"] },
  { symbol: "➙", name: "flecha derecha draft", tags: ["flecha", "casual"] },
  { symbol: "⟶", name: "flecha derecha larga fina", tags: ["flecha", "elegante"] },
  { symbol: "⟹", name: "doble flecha derecha", tags: ["flecha", "lógica"] },
  
  // Símbolos geométricos
  { symbol: "△", name: "triángulo", tags: ["geometric", "forma"] },
  { symbol: "▽", name: "triángulo invertido", tags: ["geometric", "forma"] },
  { symbol: "▲", name: "triángulo relleno", tags: ["geometric", "bold"] },
  { symbol: "▼", name: "triángulo relleno abajo", tags: ["geometric", "bold"] },
  { symbol: "◇", name: "diamante", tags: ["geometric", "elegante"] },
  { symbol: "◆", name: "diamante relleno", tags: ["geometric", "bold"] },
  { symbol: "◈", name: "diamante decorativo", tags: ["geometric", "aesthetic"] },
  { symbol: "□", name: "cuadrado", tags: ["geometric", "forma"] },
  { symbol: "■", name: "cuadrado relleno", tags: ["geometric", "bold"] },
  { symbol: "▢", name: "cuadrado redondeado", tags: ["geometric", "suave"] },
  { symbol: "▣", name: "cuadrado punto", tags: ["geometric", "decorativo"] },
  { symbol: "⬚", name: "cuadrado dotted", tags: ["geometric", "delicado"] },
  { symbol: "◯", name: "círculo grande", tags: ["geometric", "simple"] },
  { symbol: "◉", name: "círculo punto", tags: ["geometric", "objetivo"] },
  { symbol: "◌", name: "círculo dotted", tags: ["geometric", "delicado"] },
  
  // Símbolos musicales
  { symbol: "♪", name: "nota musical", tags: ["música", "nota"] },
  { symbol: "♫", name: "notas musicales", tags: ["música", "melodía"] },
  { symbol: "♬", name: "notas con corchea", tags: ["música", "ritmo"] },
  { symbol: "♭", name: "bemol", tags: ["música", "símbolo"] },
  { symbol: "♮", name: "natural", tags: ["música", "símbolo"] },
  { symbol: "♯", name: "sostenido", tags: ["música", "símbolo"] },
  
  // Símbolos especiales y decorativos
  { symbol: "✧･ﾟ", name: "sparkle decorativo", tags: ["decorativo", "aesthetic", "kawaii"] },
  { symbol: "｡･:*:･ﾟ★", name: "estrella kawaii", tags: ["decorativo", "kawaii", "estrella"] },
  { symbol: "⊹", name: "operador estrella", tags: ["math", "decorativo"] },
  { symbol: "∗", name: "asterisco", tags: ["símbolo", "math"] },
  { symbol: "✱", name: "asterisco heavy", tags: ["símbolo", "bold"] },
  { symbol: "✲", name: "asterisco open", tags: ["símbolo", "delicado"] },
  { symbol: "❃", name: "floral heart", tags: ["decorativo", "amor"] },
  { symbol: "❊", name: "flor punto", tags: ["decorativo", "flor"] },
  { symbol: "❋", name: "asterisco floral", tags: ["decorativo", "flor"] },
  { symbol: "✼", name: "asterisco flor", tags: ["decorativo", "delicado"] },
  { symbol: "꙳", name: "punto estrella cirílico", tags: ["decorativo", "único"] },
  { symbol: "⁺", name: "superíndice más", tags: ["math", "pequeño"] },
  { symbol: "₊", name: "subíndice más", tags: ["math", "pequeño"] },
  { symbol: "˖", name: "punto alto", tags: ["decorativo", "delicado"] },
  { symbol: "ᵎ", name: "exclamación pequeña", tags: ["emoción", "pequeño"] },
  { symbol: "ˎˊ˗", name: "marcas decorativas", tags: ["decorativo", "aesthetic"] },
  { symbol: "ˏˋ", name: "marcas izquierda", tags: ["decorativo", "aesthetic"] },
  { symbol: "ˎˊ", name: "marcas derecha", tags: ["decorativo", "aesthetic"] },
  { symbol: "୨୧", name: "corchetes decorativos", tags: ["decorativo", "aesthetic", "marco"] },
  { symbol: "‧₊˚", name: "puntos decorativos", tags: ["decorativo", "delicado"] },
  { symbol: "✩°｡⋆", name: "estrellas mix", tags: ["decorativo", "estrella", "aesthetic"] },
  { symbol: "𝜗ৎ", name: "lazo", tags: ["lazo", "moño"] },
  { symbol: "⋆. 𐙚 ˚", name: "lazo", tags: ["lazo", "moño", "estrella"] },
  { symbol: "𝜗𝜚", name: "lazo", tags: ["lazo", "moño"] },
  { symbol: "୨ৎ", name: "lazo", tags: ["lazo", "moño"] },
  
  // Brackets y marcos
  { symbol: "【", name: "bracket izquierdo", tags: ["marco", "decorativo"] },
  { symbol: "】", name: "bracket derecho", tags: ["marco", "decorativo"] },
  { symbol: "「", name: "esquina izquierda", tags: ["marco", "japonés"] },
  { symbol: "」", name: "esquina derecha", tags: ["marco", "japonés"] },
  { symbol: "『", name: "esquina doble izquierda", tags: ["marco", "japonés"] },
  { symbol: "』", name: "esquina doble derecha", tags: ["marco", "japonés"] },
  { symbol: "⌈", name: "techo izquierdo", tags: ["marco", "math"] },
  { symbol: "⌉", name: "techo derecho", tags: ["marco", "math"] },
  { symbol: "⌊", name: "piso izquierdo", tags: ["marco", "math"] },
  { symbol: "⌋", name: "piso derecho", tags: ["marco", "math"] },
  
  // Números y letras decorativas
  { symbol: "①", name: "número uno círculo", tags: ["número", "decorativo"] },
  { symbol: "②", name: "número dos círculo", tags: ["número", "decorativo"] },
  { symbol: "③", name: "número tres círculo", tags: ["número", "decorativo"] },
  { symbol: "④", name: "número cuatro círculo", tags: ["número", "decorativo"] },
  { symbol: "⑤", name: "número cinco círculo", tags: ["número", "decorativo"] },
  { symbol: "ⓐ", name: "letra a círculo", tags: ["letra", "decorativo"] },
  { symbol: "ⓑ", name: "letra b círculo", tags: ["letra", "decorativo"] },
  { symbol: "ⓒ", name: "letra c círculo", tags: ["letra", "decorativo"] },
  
  // Checkmarks y símbolos de aprobación
  { symbol: "✓", name: "check", tags: ["correcto", "aprobado", "símbolo"] },
  { symbol: "✔", name: "check grueso", tags: ["correcto", "bold"] },
  { symbol: "☑", name: "check box", tags: ["correcto", "caja"] },
  { symbol: "✗", name: "x", tags: ["incorrecto", "cerrar"] },
  { symbol: "✘", name: "x gruesa", tags: ["incorrecto", "bold"] },
  
  // Símbolos adicionales aesthetic
  { symbol: "𖤐", name: "estrella decorativa", tags: ["estrella", "único", "aesthetic"] },
  { symbol: "𖤓", name: "símbolo mágico", tags: ["mágico", "místico", "único"] },
  { symbol: "ꕤ", name: "flor vai", tags: ["flor", "único", "aesthetic"] },
  { symbol: "𓇽", name: "jeroglífico decorativo", tags: ["antiguo", "egipcio", "único"] },
  { symbol: "𓊆", name: "marco egipcio izquierdo", tags: ["marco", "antiguo", "egipcio"] },
  { symbol: "𓊇", name: "marco egipcio derecho", tags: ["marco", "antiguo", "egipcio"] },
  { symbol: "𓆉", name: "tortuga egipcia", tags: ["animal", "egipcio", "único"] },
  { symbol: "𓃰", name: "gato egipcio", tags: ["animal", "egipcio", "aesthetic"] },
  { symbol: "𓅿", name: "pájaro egipcio", tags: ["pájaro", "egipcio", "antiguo"] },
  { symbol: "𓃠", name: "caballo egipcio", tags: ["animal", "egipcio", "único"] },
  { symbol: "☘", name: "trébol", tags: ["naturaleza", "suerte", "trebol"] },
  { symbol: "☼", name: "sol brillante", tags: ["sol", "día", "alegre"] },
  { symbol: "♾", name: "infinito", tags: ["símbolo", "eterno", "math"] },
  { symbol: "𐐪𐑂", name: "símbolos deseret", tags: ["mariposa", "hada", "alas"] },
  { symbol: "ꔫ", name: "símbolo vai", tags: ["único", "decorativo", "aesthetic"] }
];